eslint

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -13,7 +13,7 @@ echo '🏗️👷 Hi, my name is Connor Kenway. I am responsible for testing you
 
 # Check Prettier standards
 echo '🌈 Checking Prettier standards'
-yarn check-format ||
+yarn check:format ||
 (
   echo '🤢🤮 Prettier Check Failed. Your code styling not looking good. 🤢🤮  Run yarn fix-format, add changes and try commit again.';
   false;
@@ -21,19 +21,19 @@ yarn check-format ||
 
 # Fixing formatting issues
 echo "I'm fixing your code styling. 🤓🤓";
-yarn fix-format
+yarn fix:format
 
 # Check ESLint Standards
-#echo '🛠️ Checking ESLint standards'
-#yarn check-lint ||
-#(
- # echo '😤🏀 ESLint Check Failed. Your code may have some linting issues. 👋😤 Make the required changes listed above, add changes and try to commit again.'
- # false; 
-#)
+echo '🛠️ Checking ESLint standards'
+yarn check:lint ||
+(
+  echo '😤🏀 ESLint Check Failed. Your code may have some linting issues. 👋😤 Make the required changes listed above, add changes and try to commit again.'
+  false; 
+)
 
 # Fixing linting issues
-#echo "I'm fixing your linting issues. 🤓🤓";
-#yarn lint:fix
+echo "I'm fixing your linting issues. 🤓🤓";
+yarn lint:fix
 
 # If everything passes... Now we can commit
 echo '✅✅ You win this time... I am committing this now. ✅✅'
